[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino

monitor_speed = 115200

build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D HELTEC_V3

lib_deps = 
    jgromes/RadioLib@^7.1.2
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
